name: Build/release

on:
  push:
    branches:
      - main
      - dev
    tags:
      - v*
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [14]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.29.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Pnpm Install
        run: pnpm install --frozen-lockfile false

      - name: Electron Builder Action Pnpm
        uses: njzydark/action-electron-builder-pnpm@v1.1.0-pnpm
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          app_root: './apps/desktop'
          build_script_name: 'ci:build'
          skip_package_manager_install: true
          package_manager: 'pnpm'

      - uses: actions/upload-artifact@v2
        with:
          name: PS4RPS-mac
          path: apps/desktop/output/*.dmg
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v2
        with:
          name: PS4RPS-win
          path: apps/desktop/output/*.exe
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v2
        with:
          name: PS4RPS-linux-appImage
          path: apps/desktop/output/*.AppImage
          if-no-files-found: ignore
      
      - uses: actions/upload-artifact@v2
        with:
          name: PS4RPS-linux-deb
          path: apps/desktop/output/*.deb
          if-no-files-found: ignore
