name: Desktop Build

on:
  push:
    branches:
      - main
      - dev
    tags:
      - v*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  pull_request_review:
    types:
      - edited
      - submitted
  workflow_dispatch:

jobs:
  release:
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [16]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 6.29.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Pnpm Install
        run: pnpm install --frozen-lockfile false

      - name: Electron Builder Action Pnpm
        uses: njzydark/action-electron-builder-pnpm@v1.2.0-pnpm
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          app_root: './apps/desktop'
          build_script_name: 'ci:build'
          skip_package_manager_install: true
          package_manager: 'pnpm'

      - name: upload-artifact-mac-x86
        uses: actions/upload-artifact@v3
        if: matrix.os == 'macos-latest'
        with:
          name: PS4RPS-mac-x86
          path: |
            apps/desktop/output/*.dmg
            !apps/desktop/output/*arm64.dmg
          if-no-files-found: ignore

      - name: upload-artifact-mac-arm64
        uses: actions/upload-artifact@v3
        if: matrix.os == 'macos-latest'
        with:
          name: PS4RPS-mac-arm64
          path: apps/desktop/output/*arm64.dmg
          if-no-files-found: ignore

      - name: upload-artifact-win
        uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: PS4RPS-win
          path: apps/desktop/output/*Setup*.exe
          if-no-files-found: ignore

      - name: upload-artifact-linux-appImage
        uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest'
        with:
          name: PS4RPS-linux-appImage
          path: apps/desktop/output/*.AppImage
          if-no-files-found: ignore

      - name: upload-artifact-linux-deb-amd64
        uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest'
        with:
          name: PS4RPS-linux-deb-amd64
          path: apps/desktop/output/*amd64.deb
          if-no-files-found: ignore
      
      - name: upload-artifact-linux-deb-arm64
        uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest'
        with:
          name: PS4RPS-linux-deb-arm64
          path: apps/desktop/output/*arm64.deb
          if-no-files-found: ignore
